-- Ejecutar una vez en un proyecto Supabase nuevo, antes de 002_operations.sql.
-- Los importes usan NUMERIC, no números de punto flotante.
begin;
create schema if not exists privado;
revoke all on schema privado from public;
revoke create on schema public from public;

create table public.sucursales (
  id_sucursal bigint generated by default as identity primary key,
  codigo varchar(30) not null unique,
  nombre varchar(100) not null,
  departamento varchar(100) not null,
  direccion varchar(255) not null,
  telefono varchar(20),
  tipo varchar(20) not null check (tipo in ('FARMACIA','STAND')),
  estado varchar(20) not null default 'ACTIVA' check (estado in ('ACTIVA','INACTIVA')),
  latitud numeric(10,7) not null check (latitud between -90 and 90),
  longitud numeric(10,7) not null check (longitud between -180 and 180),
  radio_entrega_km numeric(8,2) not null default 10 check (radio_entrega_km > 0),
  preparacion_minutos integer not null default 15 check (preparacion_minutos >= 0),
  velocidad_kmh numeric(8,2) not null default 20 check (velocidad_kmh > 0),
  acepta_pedidos boolean not null default true
);

-- Separado de empleados: una cuenta puede ser auditor o call center.
-- Los roles nunca se toman de user_metadata ni del formulario de registro.
create table public.perfiles (
  id_usuario uuid primary key references auth.users(id),
  rol text not null check (rol in ('ADMIN','GERENTE','VENDEDOR','BODEGA','CAJERO','CALL_CENTER','AUDITOR')),
  id_sucursal bigint references public.sucursales,
  activo boolean not null default true,
  check (rol in ('ADMIN','CALL_CENTER','AUDITOR') or id_sucursal is not null)
);

create table public.empleados (
  id_empleado bigint generated by default as identity primary key,
  codigo varchar(30) not null unique,
  id_sucursal bigint not null references public.sucursales,
  nombre varchar(100) not null,
  apellido varchar(100) not null,
  puesto varchar(50) not null,
  salario numeric(12,2) not null check (salario >= 0),
  estado text not null default 'ACTIVO' check (estado in ('ACTIVO','INACTIVO'))
);

create table public.medicamentos (
  id_medicamento bigint generated by default as identity primary key,
  codigo varchar(30) not null unique,
  nombre varchar(150) not null,
  descripcion text,
  categoria varchar(100) not null,
  principio_activo varchar(150) not null,
  precio_compra numeric(12,2) not null check (precio_compra >= 0),
  precio_venta numeric(12,2) not null check (precio_venta > 0),
  requiere_receta boolean not null default false,
  estado text not null default 'ACTIVO' check (estado in ('ACTIVO','INACTIVO'))
);

create table public.inventario (
  id_inventario bigint generated by default as identity primary key,
  id_sucursal bigint not null references public.sucursales,
  id_medicamento bigint not null references public.medicamentos,
  lote varchar(80) not null,
  fecha_vencimiento date not null,
  costo_unitario numeric(12,2) not null check (costo_unitario >= 0),
  cantidad integer not null default 0 check (cantidad >= 0),
  reservado integer not null default 0 check (reservado >= 0 and reservado <= cantidad),
  unique (id_sucursal,id_medicamento,lote)
);
create table public.stock_minimos (
  id_stock bigint generated by default as identity primary key,
  id_sucursal bigint not null references public.sucursales,
  id_medicamento bigint not null references public.medicamentos,
  stock_minimo integer not null check (stock_minimo >= 0),
  unique (id_sucursal,id_medicamento)
);
create table public.clientes (
  id_cliente bigint generated by default as identity primary key,
  codigo varchar(30) not null unique,
  nombre varchar(100) not null,
  apellido varchar(100) not null,
  telefono varchar(20) not null,
  email varchar(150),
  direccion varchar(255) not null
);
create table public.pedidos (
  id_pedido bigint generated by default as identity primary key,
  id_cliente bigint not null references public.clientes,
  id_sucursal bigint not null references public.sucursales,
  fecha timestamptz not null default now(),
  direccion_entrega varchar(255) not null,
  latitud numeric(10,7) not null check (latitud between -90 and 90),
  longitud numeric(10,7) not null check (longitud between -180 and 180),
  metodo_pago text not null check (metodo_pago in ('EFECTIVO','TARJETA','TRANSFERENCIA')),
  estado text not null default 'PENDIENTE' check (estado in ('PENDIENTE','PREPARANDO','EN_CAMINO','ENTREGADO','CANCELADO','DEVUELTO')),
  canal text not null check (canal in ('TELEFONO','PORTAL','SUCURSAL')),
  total numeric(14,2) not null check (total > 0),
  tiempo_estimado_minutos integer not null check (tiempo_estimado_minutos >= 0),
  entrega_estimada timestamptz not null,
  entregado_en timestamptz,
  repartidor varchar(150),
  nota_estado varchar(255),
  receta_referencia varchar(255),
  creado_por uuid references auth.users
);
create table public.detalle_pedido (
  id_detalle bigint generated by default as identity primary key,
  id_pedido bigint not null references public.pedidos,
  id_medicamento bigint not null references public.medicamentos,
  cantidad integer not null check (cantidad > 0),
  precio_unitario numeric(12,2) not null check (precio_unitario > 0),
  subtotal numeric(14,2) generated always as (cantidad * precio_unitario) stored,
  unique (id_pedido,id_medicamento)
);
create table public.reservas_pedido (
  id_reserva bigint generated by default as identity primary key,
  id_pedido bigint not null references public.pedidos,
  id_inventario bigint not null references public.inventario,
  cantidad integer not null check (cantidad > 0),
  unique (id_pedido,id_inventario)
);
create table public.ventas (
  id_venta bigint generated by default as identity primary key,
  id_sucursal bigint not null references public.sucursales,
  id_empleado bigint references public.empleados,
  id_cliente bigint references public.clientes,
  id_pedido bigint unique references public.pedidos,
  fecha timestamptz not null default now(),
  total numeric(14,2) not null check (total > 0),
  metodo_pago text not null check (metodo_pago in ('EFECTIVO','TARJETA','TRANSFERENCIA')),
  estado text not null default 'PAGADA' check (estado in ('PAGADA','ANULADA')),
  receta_referencia varchar(255),
  creado_por uuid references auth.users
);
create table public.detalle_venta (
  id_detalle bigint generated by default as identity primary key,
  id_venta bigint not null references public.ventas,
  id_inventario bigint not null references public.inventario,
  id_medicamento bigint not null references public.medicamentos,
  cantidad integer not null check (cantidad > 0),
  precio_unitario numeric(12,2) not null check (precio_unitario > 0),
  subtotal numeric(14,2) generated always as (cantidad * precio_unitario) stored
);
create table public.traslados (
  id_traslado bigint generated by default as identity primary key,
  id_sucursal_origen bigint not null references public.sucursales,
  id_sucursal_destino bigint not null references public.sucursales,
  estado text not null default 'EN_TRANSITO' check (estado in ('EN_TRANSITO','RECIBIDO')),
  fecha timestamptz not null default now(),
  recibido_en timestamptz,
  motivo varchar(255) not null,
  creado_por uuid references auth.users,
  recibido_por uuid references auth.users,
  check (id_sucursal_origen <> id_sucursal_destino)
);
create table public.detalle_traslado (
  id_detalle bigint generated by default as identity primary key,
  id_traslado bigint not null references public.traslados,
  id_inventario_origen bigint not null references public.inventario,
  id_medicamento bigint not null references public.medicamentos,
  lote varchar(80) not null,
  fecha_vencimiento date not null,
  costo_unitario numeric(12,2) not null check (costo_unitario >= 0),
  cantidad integer not null check (cantidad > 0)
);
create table public.movimientos_medicamentos (
  id_movimiento bigint generated by default as identity primary key,
  id_inventario bigint not null references public.inventario,
  id_sucursal bigint not null references public.sucursales,
  tipo text not null check (tipo in ('ENTRADA','VENTA','ANULACION','TRASLADO_SALIDA','TRASLADO_ENTRADA','AJUSTE')),
  cantidad integer not null check (cantidad <> 0),
  fecha timestamptz not null default now(),
  motivo varchar(255) not null,
  id_venta bigint references public.ventas,
  id_traslado bigint references public.traslados,
  creado_por uuid references auth.users
);
create table public.planillas (
  id_planilla bigint generated by default as identity primary key,
  id_sucursal bigint not null references public.sucursales,
  periodo date not null check (extract(day from periodo) = 1),
  fecha timestamptz not null default now(),
  total numeric(14,2) not null check (total > 0),
  creado_por uuid references auth.users,
  unique (id_sucursal,periodo)
);
create table public.detalle_planilla (
  id_detalle bigint generated by default as identity primary key,
  id_planilla bigint not null references public.planillas,
  id_empleado bigint not null references public.empleados,
  salario_base numeric(12,2) not null check (salario_base >= 0),
  bonificacion numeric(12,2) not null default 0 check (bonificacion >= 0),
  deduccion numeric(12,2) not null default 0 check (deduccion >= 0),
  neto numeric(12,2) generated always as (salario_base + bonificacion - deduccion) stored,
  check (salario_base + bonificacion >= deduccion),
  unique (id_planilla,id_empleado)
);
create table public.movimientos_caja (
  id_movimiento bigint generated by default as identity primary key,
  id_sucursal bigint not null references public.sucursales,
  id_empleado bigint references public.empleados,
  tipo text not null check (tipo in ('INGRESO','EGRESO')),
  concepto varchar(255) not null,
  monto numeric(14,2) not null check (monto > 0),
  metodo_pago text not null check (metodo_pago in ('EFECTIVO','TARJETA','TRANSFERENCIA')),
  fecha timestamptz not null default now(),
  id_venta bigint references public.ventas,
  id_planilla bigint unique references public.planillas,
  id_reversion bigint unique references public.movimientos_caja,
  creado_por uuid references auth.users
);
create table public.activos (
  id_activo bigint generated by default as identity primary key,
  codigo varchar(30) not null unique,
  id_sucursal bigint not null references public.sucursales,
  nombre varchar(150) not null,
  descripcion text,
  valor numeric(14,2) not null check (valor >= 0),
  valor_residual numeric(14,2) not null default 0 check (valor_residual >= 0 and valor_residual <= valor),
  vida_util_meses integer not null check (vida_util_meses > 0),
  fecha_adquisicion date not null,
  estado text not null default 'ACTIVO' check (estado in ('ACTIVO','MANTENIMIENTO','BAJA'))
);
create table public.auditoria (
  id_auditoria bigint generated by default as identity primary key,
  tabla text not null,
  registro text not null,
  accion text not null,
  id_sucursal bigint,
  actor uuid,
  fecha timestamptz not null default now(),
  antes jsonb,
  despues jsonb
);
create table privado.solicitudes (
  actor uuid not null,
  clave uuid not null,
  accion text not null,
  datos jsonb not null,
  resultado jsonb not null,
  primary key(actor,clave)
);

create index on public.inventario(id_sucursal,id_medicamento,fecha_vencimiento);
create index on public.pedidos(id_sucursal,estado,entrega_estimada);
create index on public.ventas(id_sucursal,fecha);
create index on public.movimientos_caja(id_sucursal,fecha);
create index on public.movimientos_medicamentos(id_sucursal,fecha);
create index on public.auditoria(id_sucursal,fecha);
create index on public.empleados(id_sucursal);
create index on public.activos(id_sucursal);
create index on public.detalle_venta(id_venta);
create index on public.detalle_pedido(id_pedido);
create index on public.reservas_pedido(id_pedido);
create index on public.detalle_traslado(id_traslado);
create index on public.detalle_planilla(id_planilla);

-- Estas funciones leen perfiles como propietario para evitar RLS recursivo.
create function privado.permitido(p_roles text[], p_sucursal bigint default null)
returns boolean language sql stable security definer set search_path = public, pg_temp as $$
  select exists(select 1 from public.perfiles
    where id_usuario = auth.uid() and activo
    and (rol = 'ADMIN' or rol = any(p_roles))
    and (p_sucursal is null or rol in ('ADMIN','AUDITOR','CALL_CENTER') or id_sucursal = p_sucursal));
$$;
create function privado.exigir(p_roles text[], p_sucursal bigint default null)
returns void language plpgsql security definer set search_path = public, pg_temp as $$
begin
  if not privado.permitido(p_roles,p_sucursal) then
    raise exception 'No tienes permiso para esta operación o sucursal' using errcode = '42501';
  end if;
end; $$;

-- Histórico automático. No se permite editar ni eliminar auditoría desde la API.
create function privado.auditar() returns trigger
language plpgsql security definer set search_path = public, pg_temp as $$
declare v_antes jsonb; v_despues jsonb; v_fila jsonb; v_sucursal bigint;
begin
  if tg_op <> 'INSERT' then v_antes := to_jsonb(old); end if;
  if tg_op <> 'DELETE' then v_despues := to_jsonb(new); end if;
  v_fila := coalesce(v_despues,v_antes);
  v_sucursal := (v_fila->>'id_sucursal')::bigint;
  -- Los detalles heredan la sucursal de su cabecera para no filtrar datos ajenos.
  if tg_table_name='detalle_venta' then select id_sucursal into v_sucursal from public.ventas where id_venta=(v_fila->>'id_venta')::bigint; end if;
  if tg_table_name='detalle_pedido' then select id_sucursal into v_sucursal from public.pedidos where id_pedido=(v_fila->>'id_pedido')::bigint; end if;
  if tg_table_name='reservas_pedido' then select id_sucursal into v_sucursal from public.inventario where id_inventario=(v_fila->>'id_inventario')::bigint; end if;
  if tg_table_name='detalle_planilla' then select id_sucursal into v_sucursal from public.planillas where id_planilla=(v_fila->>'id_planilla')::bigint; end if;
  if tg_table_name in ('traslados','detalle_traslado') then
    if tg_table_name='traslados' then v_sucursal := (v_fila->>'id_sucursal_origen')::bigint;
    else select id_sucursal_origen into v_sucursal from public.traslados where id_traslado=(v_fila->>'id_traslado')::bigint; end if;
  end if;
  insert into public.auditoria(tabla,registro,accion,id_sucursal,actor,antes,despues)
  values(tg_table_name, v_fila->>tg_argv[0], tg_op,
    v_sucursal, auth.uid(), v_antes,v_despues);
  return coalesce(new,old);
end; $$;

do $$ declare t text; pk text; begin
  for t,pk in select * from (values
    ('sucursales','id_sucursal'),('perfiles','id_usuario'),('empleados','id_empleado'),
    ('medicamentos','id_medicamento'),('inventario','id_inventario'),('stock_minimos','id_stock'),
    ('clientes','id_cliente'),('pedidos','id_pedido'),('detalle_pedido','id_detalle'),
    ('reservas_pedido','id_reserva'),('ventas','id_venta'),('detalle_venta','id_detalle'),
    ('traslados','id_traslado'),('detalle_traslado','id_detalle'),
    ('movimientos_medicamentos','id_movimiento'),('movimientos_caja','id_movimiento'),
    ('planillas','id_planilla'),('detalle_planilla','id_detalle'),('activos','id_activo')
  ) as tablas(tabla,clave) loop
    execute format('alter table public.%I enable row level security',t);
    execute format('create trigger historial after insert or update or delete on public.%I for each row execute function privado.auditar(%L)',t,pk);
    execute format('revoke all on public.%I from anon,authenticated',t);
    execute format('grant select on public.%I to authenticated',t);
    execute format('grant all on public.%I to service_role',t);
    if t<>'perfiles' then
      execute format('grant all on sequence %s to service_role',pg_get_serial_sequence('public.'||t,pk));
    end if;
    if t in ('sucursales','empleados','medicamentos','stock_minimos','clientes','activos') then
      execute format('grant usage,select on sequence %s to authenticated',pg_get_serial_sequence('public.'||t,pk));
    end if;
  end loop;
end; $$;
alter table public.auditoria enable row level security;

-- Sin permisos, registrarse/iniciar sesión NO da acceso a la empresa.
revoke all on public.auditoria from anon,authenticated;
grant select on public.auditoria to authenticated;
grant all on public.auditoria to service_role;
grant all on sequence public.auditoria_id_auditoria_seq to service_role;
grant usage on schema privado to authenticated;

create policy leer_perfil on public.perfiles for select to authenticated
  using(id_usuario = auth.uid() or privado.permitido(array['AUDITOR']));
create policy administrar_perfil on public.perfiles for all to authenticated
  using(privado.permitido(array[]::text[])) with check(privado.permitido(array[]::text[]));
grant insert,update on public.perfiles to authenticated;

do $$ declare t text; begin
  foreach t in array array['sucursales','medicamentos','clientes'] loop
    execute format('create policy lectura on public.%I for select to authenticated using(privado.permitido(array[''GERENTE'',''VENDEDOR'',''BODEGA'',''CAJERO'',''CALL_CENTER'',''AUDITOR'']))',t);
  end loop;
  foreach t in array array['sucursales','medicamentos'] loop
    execute format('create policy escritura on public.%I for all to authenticated using(privado.permitido(array[]::text[])) with check(privado.permitido(array[]::text[]))',t);
    execute format('grant insert,update on public.%I to authenticated',t);
  end loop;
  foreach t in array array['empleados','activos','stock_minimos'] loop
    execute format('create policy lectura on public.%I for select to authenticated using(privado.permitido(array[''GERENTE'',''AUDITOR''],id_sucursal))',t);
    execute format('create policy escritura on public.%I for all to authenticated using(privado.permitido(array[''GERENTE''],id_sucursal)) with check(privado.permitido(array[''GERENTE''],id_sucursal))',t);
    execute format('grant insert,update on public.%I to authenticated',t);
  end loop;
end; $$;
create policy escritura on public.clientes for all to authenticated
  using(privado.permitido(array['GERENTE','VENDEDOR','CALL_CENTER']))
  with check(privado.permitido(array['GERENTE','VENDEDOR','CALL_CENTER']));
grant insert,update on public.clientes to authenticated;
create policy lectura on public.inventario for select to authenticated
  using(privado.permitido(array['GERENTE','VENDEDOR','BODEGA','CAJERO','AUDITOR'],id_sucursal) or privado.permitido(array['CALL_CENTER']));
create policy lectura on public.ventas for select to authenticated
  using(privado.permitido(array['GERENTE','VENDEDOR','CAJERO','AUDITOR'],id_sucursal));
create policy lectura on public.pedidos for select to authenticated
  using(privado.permitido(array['GERENTE','VENDEDOR','BODEGA','AUDITOR'],id_sucursal) or privado.permitido(array['CALL_CENTER']));
create policy lectura on public.traslados for select to authenticated
  using(privado.permitido(array['GERENTE','BODEGA','AUDITOR'],id_sucursal_origen) or privado.permitido(array['GERENTE','BODEGA','AUDITOR'],id_sucursal_destino));
create policy lectura on public.movimientos_medicamentos for select to authenticated
  using(privado.permitido(array['GERENTE','BODEGA','AUDITOR'],id_sucursal));
create policy lectura on public.movimientos_caja for select to authenticated
  using(privado.permitido(array['GERENTE','CAJERO','AUDITOR'],id_sucursal));
create policy lectura on public.planillas for select to authenticated
  using(privado.permitido(array['GERENTE','AUDITOR'],id_sucursal));
create policy lectura on public.auditoria for select to authenticated
  using((id_sucursal is not null and privado.permitido(array['GERENTE','AUDITOR'],id_sucursal))
    or (antes->>'id_sucursal' is not null and privado.permitido(array['GERENTE','AUDITOR'],(antes->>'id_sucursal')::bigint))
    or privado.permitido(array['AUDITOR']));
create policy lectura on public.detalle_venta for select to authenticated
  using(exists(select 1 from public.ventas v where v.id_venta = detalle_venta.id_venta));
create policy lectura on public.detalle_pedido for select to authenticated
  using(exists(select 1 from public.pedidos p where p.id_pedido = detalle_pedido.id_pedido));
create policy lectura on public.reservas_pedido for select to authenticated
  using(exists(select 1 from public.pedidos p where p.id_pedido = reservas_pedido.id_pedido));
create policy lectura on public.detalle_traslado for select to authenticated
  using(exists(select 1 from public.traslados t where t.id_traslado = detalle_traslado.id_traslado));
create policy lectura on public.detalle_planilla for select to authenticated
  using(exists(select 1 from public.planillas p where p.id_planilla = detalle_planilla.id_planilla));

revoke execute on all functions in schema privado from public,anon,authenticated;
grant execute on function privado.permitido(text[],bigint) to authenticated;
commit;
